In [1]:
import numpy as np
import random
import time
import sys
sys.setrecursionlimit(1500)

In [2]:
# CONSTANTS
PIECE_COUNT = 6


In [3]:
def check(board,row,col,iter):
  if iter == 0:
    return False
  
  if len(positions) == PIECE_COUNT:
    pos = 0
    for x in range(PIECE_COUNT):
      for i in positions:
        a = positions[pos]
        if i == a:
          return False
        else:
          return True
        pos += 1
    return True
  if row in range(0,PIECE_COUNT+1) and col in range(0,PIECE_COUNT+1):  
    #             UP,       RIGHT,      LEFT,       DOWN.
    paths = [[row-1,col],[row,col+1],[row,col-1],[row+1,col]]
              #[[1,2],[2,3],[2,1],[3,2]]
              
    #print(f"HERE ARE THE POSITIONS: {positions}")
    
    for i,[x,y] in enumerate(paths):
    
      if [x,y] not in positions:
        #print(f"X AND Y: {[x,y]}")
        if board[x,y] == 1:
          if i == 0:
            # UP.
            if board[row,col] == board[x,y] and board[row,col] == 1:
              if [x,y] not in positions:
                positions.append([x,y])
                #print('UPP.')
                #print(len(positions))
                if len(positions) < PIECE_COUNT:
                  check(board,x,y,iter-1)
                  #print("IN HEREE")
          
          elif i == 1:
            if board[row,col] == board[x,y] and board[row,col] == 1:
              if [x,y] not in positions:
                positions.append([x,y])
                #print("RIGHTT.")
                if len(positions) < PIECE_COUNT:
                  check(board,x,y,iter-1)

          elif i == 2:
            if board[row,col] == board[x,y] and board[row,col] == 1:
              if [x,y] not in positions:
                positions.append([x,y])
                #print("LEFTT")
                if len(positions) < PIECE_COUNT:
                  check(board,x,y,iter-1)
          elif i == 3:
            if board[row,col] == board[x,y] and board[row,col] == 1:
              if [x,y] not in positions:
                positions.append([x,y])
                #print("DOWNN")
                if len(positions) < PIECE_COUNT:
                  check(board,x,y,iter-1)
          else:
            check(board,row,col,iter-1)
  else:
    if row < 0:
      check(board,row+1,col,iter-1)
    elif col < 0:
      check(board,row,col+1)
    else:
      return False
  if len(positions) < PIECE_COUNT:
    return False
  #print(f"FINAL POSITIONS: {positions}")  
  return positions,True

      





In [4]:
def board(PIECE_COUNT):   
  if PIECE_COUNT % 2 != 0:
    board = np.zeros([PIECE_COUNT,PIECE_COUNT])
    coor = int((PIECE_COUNT-1) / 2)
    board[coor,coor] = 1
    
  else:
    board = np.zeros([PIECE_COUNT + 1,PIECE_COUNT + 1])
    coor = int(PIECE_COUNT / 2)
    board[coor,coor] = 1

  return board

In [5]:
  def position(matrix):
    positions = []

    for i in range(PIECE_COUNT):
      for j in range(PIECE_COUNT):
        positions.append(matrix[i,j])

    return positions

In [6]:
def form_objects():
  objects = []
  if PIECE_COUNT % 2 != 0:
    coor = int((PIECE_COUNT-1) / 2)
  else:
    coor = int(PIECE_COUNT / 2)
  
  for i in range(PIECE_COUNT-1):
    while len(objects) < PIECE_COUNT-1:
      x,y = random.randint(0,PIECE_COUNT-1),random.randint(0,PIECE_COUNT-1)
      if (x,y) not in objects and (x,y) != (coor,coor):
        objects.append((x,y))


  return objects

In [7]:
def trim_zeros(arr, margin=0):

    s = []
    for dim in range(arr.ndim):
        start = 0
        end = -1
        slice_ = [slice(None)]*arr.ndim

        go = True
        while go:
            slice_[dim] = start
            go = not np.any(arr[tuple(slice_)])
            start += 1
        start = max(start-1-margin, 0)

        go = True
        while go:
            slice_[dim] = end
            go = not np.any(arr[tuple(slice_)])
            end -= 1
        end = arr.shape[dim] + min(-1, end+1+margin) + 1

        s.append(slice(start,end))
    return arr[tuple(s)]

In [8]:
def location(board):
  posx = []
  posy = []
  x,y = board.shape
  for i in range(x):
    for j in range(y):
      if board[i,j] == 1:
        posx.append(i)
        #print(f"X: {i}")
        posy.append(j)
        #print(f"Y: {j}")

  xcoor = max(posx) - min(posx) + 1
  #print(xcoor)
  ycoor = max(posy)-min(posy) + 1
  #print(ycoor)
  arr = np.zeros([xcoor,ycoor])
  
  return arr



In [9]:

a = [[1,0,0],[1,1,0],[0,0,0]]
print(a)
print(np.asarray)
b = np.fliplr(a)
print(b)

[[1, 0, 0], [1, 1, 0], [0, 0, 0]]
<built-in function asarray>
[[0 0 1]
 [0 1 1]
 [0 0 0]]


In [11]:
valid_objects = []

count = 0
start = time.time()

board_size = 9
mid = 4
recur_lim = 6

num_iters = 1000000

for i in range(num_iters):
  positions = [[mid,mid]]
  points = form_objects()
  boards = np.zeros([board_size, board_size])
  boards[mid,mid] = 1
  for i,x in points:
      boards[i,x] = 1 
  if check(boards,mid,mid, recur_lim):
    new_board = trim_zeros(boards)
    valid_objects.append(new_board)
    count+=1


  

for i,element in enumerate(valid_objects):

  print(element)
  print('\n')
#print(np.array_equal(valid_objects[1],valid_objects[2]))
end = time.time() - start



print(f"Object count: {count}")
print(f"Execution time: {end}")


  

[[1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


[[0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 1.]
 [0. 1.]]


[[0. 0. 1. 1.]
 [0. 1. 1. 0.]
 [1. 1. 0. 0.]]


[[1. 1. 0.]
 [0. 1. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


[[0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]]


[[1. 1. 1.]
 [0. 0. 1.]
 [0. 1. 1.]]


[[0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


[[1. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 1. 0. 0.]]


[[0. 0. 1. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]]


[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 1.]]


[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 1. 1.]]


[[0. 1.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]]


[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 1.]]


[[0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]]


[[1. 0. 0. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 1. 1. 1.]]


[[1. 1. 1. 1.]
 [1. 1. 0. 0.]]


[[0. 1. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]]


[[1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


[[1. 1. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [0. 1. 0.]]


[[1. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 1. 1.

In [12]:
data_list = []

for item in valid_objects:
  data_list.append(item.tolist())

print(f'data_list count: {len(data_list)}')

data_list count: 928


In [13]:
# Get rid of the same pattern.

unique_list = []

for item in data_list:
  if item not in unique_list:
    unique_list.append(item)

# for i, item in enumerate(data_list):
#   if item in data_list[:i] or item in data_list[i+1:]:
#     data_list.remove(item)

print(f"Results count: {len(unique_list)}")
print(f'Type of unique_list elements: {type(unique_list[0])}')

Results count: 187
Type of unique_list elements: <class 'list'>


In [14]:
for i in unique_list:
  print(np.asarray(i))
  print('\n')

[[1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


[[0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 1.]
 [0. 1.]]


[[0. 0. 1. 1.]
 [0. 1. 1. 0.]
 [1. 1. 0. 0.]]


[[1. 1. 0.]
 [0. 1. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


[[0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]]


[[1. 1. 1.]
 [0. 0. 1.]
 [0. 1. 1.]]


[[0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


[[1. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 1. 0. 0.]]


[[0. 0. 1. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]]


[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 1.]]


[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 1. 1.]]


[[0. 1.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]]


[[0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]]


[[1. 0. 0. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 1. 1. 1.]]


[[1. 1. 1. 1.]
 [1. 1. 0. 0.]]


[[0. 1. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]]


[[1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


[[1. 1. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [0. 1. 0.]]


[[1. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


[[1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


[[0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 0.]]


[

In [15]:
# Rotation check.
final_list = []
rots = []

for element in unique_list:

  for i in range(1,4):
    a = np.rot90(element,i).tolist()
    rots.append(a)

  flipped = np.fliplr(element).tolist()

  for i in range(4):
    b = np.rot90(flipped,i).tolist()
    rots.append(b)


  if element in rots:
    # Remove all the occurences of the original element
    rots = [item for item in rots if item != element]

  rots_2 = []
  for item in rots:
    if item not in rots_2:
      rots_2.append(item)

  for vals in rots_2:
    if vals not in final_list:
      final_list.append(vals)

  for item in final_list:
    if item in unique_list:
      unique_list.remove(item)
print(f"Results count: {len(unique_list)}")
print(f'Type of unique_list elements: {type(unique_list[0])}')


Results count: 35
Type of unique_list elements: <class 'list'>


In [16]:
for i in unique_list:
  print(np.asarray(i))
  print('\n')

[[1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


[[0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 1.]
 [0. 1.]]


[[0. 0. 1. 1.]
 [0. 1. 1. 0.]
 [1. 1. 0. 0.]]


[[1. 1. 0.]
 [0. 1. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


[[0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]]


[[1. 1. 1.]
 [0. 0. 1.]
 [0. 1. 1.]]


[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 1.]]


[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 1. 1.]]


[[0. 1.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]]


[[0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]]


[[1. 0. 0. 1.]
 [1. 1. 1. 1.]]


[[1. 1. 1. 1.]
 [1. 1. 0. 0.]]


[[0. 1. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]]


[[0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 0.]]


[[1. 1. 1. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


[[0. 1. 0. 1.]
 [1. 1. 1. 1.]]


[[0. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]]


[[1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]]


[[0. 0. 1.]
 [0. 1. 1.]
 [1. 1. 0.]
 [0. 1. 0.]]


[[1. 1. 1. 1.]
 [0. 1. 1. 0.]]


[[0. 1. 1.]
 [1. 1. 0.]
 [0. 1. 1.]]


[[0. 1. 1.]
 [0. 1. 1.]
 [1. 1. 0.]]


[[0. 1. 0.]
 [1. 1. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


[